[toolchain]
name = "Zig/Clang"
compiler-c =   [ "zig", "cc" ]
compiler-cpp = [ "zig", "c++" ]
linker-c =     [ "zig", "cc" ]
linker-cpp =   [ "zig", "c++" ]
archiver-c =   [ "zig", "ar", "rcs" ]
archiver-cpp = [ "zig", "ar", "rcs" ]
exe-fmt     = "{name}"
obj-fmt     = "{name}.o"
archive-fmt = "lib{name}.a"


# =============================================================================================
[compiler]
input =   [ "{srcfile}" ]
output =  [ "-o", "{objfile}" ]

standard =   [ "-std={lang}" ]
comp-only =  [ "-c" ]
eh-default = []
debug-info = [ "-g" ]

include =  [ "-I{incdir}" ]
define =   [ "-D{define}" ]

opt-0 =     [ "-O0" ]
opt-1 =     [ "-O1" ]
opt-2 =     [ "-O2" ]
opt-3 =     [ "-O3" ]
opt-size =  [ "-Os" ]
opt-speed = [ "-Ofast" ]
opt-linktime = [ "-flto" ]

pch-create =  []
pch-include = [ "-I{outdir}/pch" ]

runtime-static-debug =    []
runtime-static-release =  []
runtime-dynamic-debug =   []
runtime-dynamic-release = []

aslr-app = [ "-fpie" ]
aslr-lib = [ "-fpic" ]

iso-compliant = [ "-pedantic-errors" ]

warn-none =     [ "-w" ]
warn-basic =    [ "-Wall" ]
warn-high =     [ "-Wall", "-Wextra", "-Wpedantic", "-Wconversion", "-Wsign-conversion", "-Wshadow",
                 "-Wformat=2", "-Wnull-dereference", "-Wdouble-promotion", "-Wimplicit-fallthrough=5" ]
warn-as-error = [ "-Werror" ]


# =============================================================================================
[linker]
object =  [ "{objfile}" ]
libdir =  [ "-L{libdir}" ]
library = [ "-l{library}" ]
output =  [ "-o{binary}" ]

aslr = [ "-pie" ]

shared-lib = [ "-shared" ]
import-lib = [ "-Wl,--out-implib,{library}" ]

opt-linktime = [ "-flto" ]

default-libs = []


# =============================================================================================
[archiver]
object =  [ "{objfile}" ]
output =  [ "{archive}" ]

