[package]
name = "vango"
version = "2.6.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.9.5", features = ["preserve_order"] }
# clap = { version = "4.5.47", features = ["derive"] }
termcolor = "1.4.1"
thiserror = "2.0.0"

