[toolchain]
name = "MSVC"
compiler-c =   [ "cl.exe" ]
compiler-cpp = [ "cl.exe" ]
linker-c =     [ "LINK.exe" ]
linker-cpp =   [ "LINK.exe" ]
archiver-c =   [ "LIB.exe" ]
archiver-cpp = [ "LIB.exe" ]
exe-fmt     = "{name}.exe"
obj-fmt     = "{name}.obj"
archive-fmt = "{name}.lib"


# =============================================================================================
[compiler]
input =   [ "{srcfile}" ]
output =  [ "/Fo:{objfile}" ]

standard =   [ "/std:{lang}" ]
comp-only =  [ "/c" ]
eh-default = [ "/EHsc" ]
debug-info = [ "/Zi", "/Fd:{outdir}\\obj\\", "/FS" ]

include =  [ "/I{incdir}" ]
define =   [ "/D{define}" ]

opt-0 =     [ "/Od" ]
opt-1 =     [ "/Ox" ]
opt-2 =     [ "/O1" ]
opt-3 =     [ "/O2", "Oi" ]
opt-size =  [ "/Os" ]
opt-speed = [ "/Ot" ]
opt-linktime = [ "/GL" ]

warn-none =     [ "/w" ]
warn-basic =    [ "/W1" ]
warn-high =     [ "/W4" ]
warn-as-error = [ "/WX" ]

pch-create =  [ "/Yc{pcheader}", "/Fp:{outdir}/pch/{pcheader}.pch" ]
pch-include = [ "/Yu{pcheader}", "/Fp:{outdir}/pch/{pcheader}.pch" ]

runtime-static-debug =    [ "/MTd" ]
runtime-static-release =  [ "/MT" ]
runtime-dynamic-debug =   [ "/MDd" ]
runtime-dynamic-release = [ "/MD" ]

iso-compliant = [ "/permissive-" ]

aslr-app = []
aslr-lib = []

no-rtti = [ "/GR-" ]


# =============================================================================================
[linker]
object =  [ "{objfile}" ]
libdir =  [ "/LIBPATH:{libdir}" ]
library = [ "{library}" ]
output =  [ "/OUT:{binary}" ]

opt-linktime = [ "/LTCG", "OPT:REF" ]

aslr = [ "/DYNAMICBASE" ]

shared-lib = [ "/DLL" ]
import-lib = [ "/IMPLIB:{library}" ]

default-libs = [
    "kernel32",
    "user32",
    "winspool",
    "comdlg32",
    "advapi32",
    "shell32",
    "ole32",
    "oleaut32",
    "uuid",
    "odbc32",
    "odbccp32",
    "gdi32",
];


# =============================================================================================
[archiver]
object =  [ "{objfile}" ]
output =  [ "/OUT:{archive}" ]

