[toolchain]
name = "Clang"

# MSVC ========================================
compiler-c =   [ "clang-cl.exe" ]
compiler-cpp = [ "clang-cl.exe" ]
linker-c =     [ "lld-link.exe" ]
linker-cpp =   [ "lld-link.exe" ]
archiver-c =   [ "llvm-lib.exe" ]
archiver-cpp = [ "llvm-lib.exe" ]
exe-fmt     = "{name}.exe"
obj-fmt     = "{name}.obj"
archive-fmt = "{name}.lib"

# All other options are the same as in 'msvc.toml'

# GNU =========================================
compiler-c =   [ "clang" ]
compiler-cpp = [ "clang++" ]
linker-c =     [ "clang" ]
linker-cpp =   [ "clang++" ]
archiver-c =   [ "llvm-ar", "rcs" ]
archiver-cpp = [ "llvm-ar", "rcs" ]
exe-fmt     = "{name}"
obj-fmt     = "{name}.o"
archive-fmt = "lib{name}.a"


# =============================================================================================
[compiler]
input =   [ "{srcfile}" ]
output =  [ "-o", "{objfile}" ]

standard =   [ "-std={lang}" ]
comp-only =  [ "-c" ]
eh-default = []
debug-info = [ "-g" ]

include =  [ "-I{incdir}" ]
define =   [ "-D{define}" ]

opt-0 =     [ "-O0" ]
opt-1 =     [ "-O1" ]
opt-2 =     [ "-O2" ]
opt-3 =     [ "-O3" ]
opt-size =  [ "-Os" ]
opt-speed = [ "-Ofast" ]
opt-linktime = [ "-flto" ]

aslr-app = [ "-fpie" ]
aslr-lib = [ "-fPIC" ]

rtti = [ "-rtti" ]

pthread = [ "-pthread" ]

warn-none =     [ "-w" ]
warn-basic =    [ "-Wall" ]
warn-high =     [ "-Wall", "-Wextra", "-Wpedantic", "-Wconversion", "-Wsign-conversion", "-Wshadow",
                 "-Wformat=2", "-Wnull-dereference", "-Wdouble-promotion", "-Wimplicit-fallthrough" ]
warn-as-error = [ "-Werror" ]

pch-create =  []
pch-include = [ "-I{outdir}/pch" ]

runtime-static-debug =    []
runtime-static-release =  []
runtime-dynamic-debug =   []
runtime-dynamic-release = []

iso-compliant = [ "-pedantic-errors" ]


# =============================================================================================
[linker]
object =  [ "{objfile}" ]
libdir =  [ "-L{libdir}" ]
library = [ "-l{library}" ]
output =  [ "-o{binary}" ]

shared-lib = [ "-shared" ]
import-lib = [ "-Wl,--out-implib,{library}" ]

opt-linktime = [ "-flto" ]
aslr = [ "-pie" ]
pthread = [ "-pthread" ]

default-libs = []


# =============================================================================================
[archiver]
object =  [ "{objfile}" ]
output =  [ "{archive}" ]

opt-linktime = []

