
[debug]
include = [ "src" ]
defines = [ "VANGO_DEBUG" ]
opt-level = 0
opt-size = false
opt-speed = false
opt-linktime = false
debug-info = true
warn-level = "basic"
warn-as-error = false
iso-compliant = false
aslr = true
pthread = false
no-rtti = false
no-except = false
implib = true
# runtime = "dynamic-debug"


[release]
include = [ "src" ]
defines = [ "VANGO_RELEASE" ]
opt-level = 3
opt-size = false
opt-speed = false
opt-linktime = true
debug-info = false
warn-level = "basic"
warn-as-error = false
iso-compliant = false
aslr = true
rtti = true
pthread = false
no-rtti = false
no-except = false
implib = true
# runtime = "dynamic-release"

