name: Release

on:
  push:
    tags:
      - 'v*.*.*' # triggers on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package
        run: |
          mkdir dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp target/release/*.exe dist/ -r
          else
            cp target/release/* dist/ -r
          fi

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
